--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: LCPCollectionDB; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "LCPCollectionDB" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Portuguese_Brazil.1252';


ALTER DATABASE "LCPCollectionDB" OWNER TO postgres;

\connect "LCPCollectionDB"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Animes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Animes" (
    "Id" integer NOT NULL,
    "Title" text,
    "Description" text,
    "CoverUrl" text,
    "ImageUrl" text,
    "Companies" text,
    "Publishers" text,
    "Platforms" text,
    "ReleaseDate" timestamp without time zone,
    "TrailerUrl" text,
    "Genre" text,
    "Rating" double precision
);


ALTER TABLE public."Animes" OWNER TO postgres;

--
-- Name: Animes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Animes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Animes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Books; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Books" (
    "Id" integer NOT NULL,
    "Title" text,
    "Description" text,
    "CoverUrl" text,
    "ImageUrl" text,
    "Companies" text,
    "Publishers" text,
    "Platforms" text,
    "ReleaseDate" timestamp without time zone,
    "TrailerUrl" text,
    "Genre" text,
    "Rating" double precision
);


ALTER TABLE public."Books" OWNER TO postgres;

--
-- Name: Books_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Books" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Books_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: FilesData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."FilesData" (
    "Id" integer NOT NULL,
    "GId" uuid NOT NULL,
    "ImageBytes" bytea,
    "FileName" text NOT NULL,
    "FileType" text NOT NULL,
    "FileFullPath" text,
    "FileSize" bigint NOT NULL
);


ALTER TABLE public."FilesData" OWNER TO postgres;

--
-- Name: FilesData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."FilesData" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FilesData_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Games; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Games" (
    "Id" integer NOT NULL,
    "Title" text,
    "Description" text,
    "CoverUrl" text,
    "ImageUrl" text,
    "Companies" text,
    "Publishers" text,
    "Platforms" text,
    "ReleaseDate" timestamp without time zone,
    "TrailerUrl" text,
    "Genre" text,
    "Rating" double precision
);


ALTER TABLE public."Games" OWNER TO postgres;

--
-- Name: Games_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Games" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Games_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Movies" (
    "Id" integer NOT NULL,
    "Title" text,
    "Description" text,
    "CoverUrl" text,
    "ImageUrl" text,
    "Companies" text,
    "Publishers" text,
    "Platforms" text,
    "ReleaseDate" timestamp without time zone,
    "TrailerUrl" text,
    "Genre" text,
    "Rating" double precision
);


ALTER TABLE public."Movies" OWNER TO postgres;

--
-- Name: Movies_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Movies" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Movies_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TVSeries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TVSeries" (
    "Id" integer NOT NULL,
    "Title" text,
    "Description" text,
    "CoverUrl" text,
    "ImageUrl" text,
    "Companies" text,
    "Publishers" text,
    "Platforms" text,
    "ReleaseDate" timestamp without time zone,
    "TrailerUrl" text,
    "Genre" text,
    "Rating" double precision
);


ALTER TABLE public."TVSeries" OWNER TO postgres;

--
-- Name: TVSeries_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TVSeries" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TVSeries_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Animes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Animes" ("Id", "Title", "Description", "CoverUrl", "ImageUrl", "Companies", "Publishers", "Platforms", "ReleaseDate", "TrailerUrl", "Genre", "Rating") FROM stdin;
1	Dragon Ball	Dragon Ball	covers/db.jpg	images/db.jpg	Toei Animation	Toei Animation	TV	1986-02-26 00:00:00	https://www.youtube.com/watch?v=gqIEgmqljM8	Animation	9
\.


--
-- Data for Name: Books; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Books" ("Id", "Title", "Description", "CoverUrl", "ImageUrl", "Companies", "Publishers", "Platforms", "ReleaseDate", "TrailerUrl", "Genre", "Rating") FROM stdin;
\.


--
-- Data for Name: FilesData; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."FilesData" ("Id", "GId", "ImageBytes", "FileName", "FileType", "FileFullPath", "FileSize") FROM stdin;
\.


--
-- Data for Name: Games; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Games" ("Id", "Title", "Description", "CoverUrl", "ImageUrl", "Companies", "Publishers", "Platforms", "ReleaseDate", "TrailerUrl", "Genre", "Rating") FROM stdin;
\.


--
-- Data for Name: Movies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Movies" ("Id", "Title", "Description", "CoverUrl", "ImageUrl", "Companies", "Publishers", "Platforms", "ReleaseDate", "TrailerUrl", "Genre", "Rating") FROM stdin;
\.


--
-- Data for Name: TVSeries; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."TVSeries" ("Id", "Title", "Description", "CoverUrl", "ImageUrl", "Companies", "Publishers", "Platforms", "ReleaseDate", "TrailerUrl", "Genre", "Rating") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240203094954_InitialCreatePostgreSQL	8.0.1
\.


--
-- Name: Animes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Animes_Id_seq"', 2, false);


--
-- Name: Books_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Books_Id_seq"', 1, false);


--
-- Name: FilesData_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."FilesData_Id_seq"', 1, false);


--
-- Name: Games_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Games_Id_seq"', 1, false);


--
-- Name: Movies_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Movies_Id_seq"', 1, false);


--
-- Name: TVSeries_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TVSeries_Id_seq"', 1, false);


--
-- Name: Animes PK_Animes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Animes"
    ADD CONSTRAINT "PK_Animes" PRIMARY KEY ("Id");


--
-- Name: Books PK_Books; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Books"
    ADD CONSTRAINT "PK_Books" PRIMARY KEY ("Id");


--
-- Name: FilesData PK_FilesData; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."FilesData"
    ADD CONSTRAINT "PK_FilesData" PRIMARY KEY ("Id");


--
-- Name: Games PK_Games; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Games"
    ADD CONSTRAINT "PK_Games" PRIMARY KEY ("Id");


--
-- Name: Movies PK_Movies; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Movies"
    ADD CONSTRAINT "PK_Movies" PRIMARY KEY ("Id");


--
-- Name: TVSeries PK_TVSeries; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TVSeries"
    ADD CONSTRAINT "PK_TVSeries" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

